"""Mirror every Finnhub logo URL in `LOGO_BY_TICKER` to a local PNG in
`web/public/logos/`, then rewrite `ao/data/sp500_logos.py` so each ticker
points at the local path. Lets the repo own the logo assets — the app
serves them from its own origin, survives Finnhub outages, and the
browser HTTP-caches them aggressively under the Vite static handler.

Usage (from `workers/`):
    python -m scripts.mirror_logos          # download missing only
    python -m scripts.mirror_logos --force  # redownload everything

Idempotent. Re-runnable. Safe to re-run after `seed_logos.py` refreshes
the Finnhub URL pool — it will just download any newly added ones.
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

import httpx

from ao.data.sp500_logos import LOGO_BY_TICKER


LOGO_DIR = Path(__file__).resolve().parents[2] / "web" / "public" / "logos"
OUT_FILE = Path(__file__).resolve().parents[1] / "ao" / "data" / "sp500_logos.py"

HEADER = '''"""Per-ticker logo URL map for the Add Companies S&P 500 browse grid.

Generated by `workers/scripts/mirror_logos.py`, which downloads each
Finnhub-hosted PNG into `web/public/logos/` and rewrites this file to
point at the local /logos/<TICKER>.png path. Re-run mirror_logos after
`seed_logos.py` to pick up new tickers from Finnhub.

Tickers not present in the map render with the 2-letter monogram (same
as the on-error fallback inside the `<Glyph>` primitive).
"""
from __future__ import annotations

LOGO_BY_TICKER: dict[str, str] = {
'''
FOOTER = "}\n"


def _local_filename(ticker: str) -> str:
    # Keep dots (BRK.B → BRK.B.png) — valid filenames + valid URL paths.
    return f"{ticker}.png"


async def main(force: bool) -> int:
    LOGO_DIR.mkdir(parents=True, exist_ok=True)
    items = sorted(LOGO_BY_TICKER.items())
    total = len(items)
    local_map: dict[str, str] = {}

    async with httpx.AsyncClient(timeout=30.0, follow_redirects=True) as client:
        for i, (ticker, url) in enumerate(items, start=1):
            fname = _local_filename(ticker)
            disk_path = LOGO_DIR / fname
            local_url = f"/logos/{fname}"

            # Already migrated to /logos/ — nothing to download.
            if url.startswith("/logos/"):
                if disk_path.exists() and not force:
                    local_map[ticker] = url
                    print(f"[{i:>3}/{total}] {ticker:<6} already local")
                    continue
                # File missing on disk but map says local — rebuild needs the
                # original Finnhub URL. Re-run seed_logos.py first.
                print(
                    f"[{i:>3}/{total}] {ticker:<6} SKIP — listed local but file "
                    f"missing; rerun seed_logos.py to repopulate Finnhub URLs"
                )
                continue

            if disk_path.exists() and not force:
                local_map[ticker] = local_url
                print(f"[{i:>3}/{total}] {ticker:<6} cached")
                continue

            try:
                r = await client.get(url)
                r.raise_for_status()
            except Exception as exc:  # noqa: BLE001
                print(f"[{i:>3}/{total}] {ticker:<6} ERROR: {exc}")
                continue

            disk_path.write_bytes(r.content)
            size_kb = len(r.content) / 1024
            local_map[ticker] = local_url
            print(f"[{i:>3}/{total}] {ticker:<6} downloaded {size_kb:.1f} KB")

    body = "".join(
        f"    {ticker!r}: {url!r},\n" for ticker, url in sorted(local_map.items())
    )
    OUT_FILE.write_text(HEADER + body + FOOTER, encoding="utf-8")
    print(f"\nWrote {len(local_map)} entries to {OUT_FILE}")
    print(f"PNG files in {LOGO_DIR}")
    return 0


if __name__ == "__main__":
    force = "--force" in sys.argv[1:]
    raise SystemExit(asyncio.run(main(force)))
