"""One-shot backfill: populate `ao/data/sp500_logos.py` with logo URLs.

For every ticker in `SP500_SEED`, calls Finnhub `/stock/profile2` and
extracts the `logo` URL. Writes the result back into
`workers/ao/data/sp500_logos.py` as `LOGO_BY_TICKER`.

Usage (from the `workers/` directory):
    python -m scripts.seed_logos

Re-run any time the SP500 roster changes. Requires `FINNHUB_API_KEY`
in the env (same as the running API).
"""
from __future__ import annotations

import asyncio
from pathlib import Path

from ao.data.sp500_seed import SP500_SEED
from ao.integrations.finnhub_client import company_profile, is_configured


OUTPUT = Path(__file__).resolve().parents[1] / "ao" / "data" / "sp500_logos.py"
HEADER = '''"""Per-ticker logo URL map for the Add Companies S&P 500 browse grid.

Generated by `workers/scripts/seed_logos.py`, which calls Finnhub
`/stock/profile2` for every ticker in `sp500_seed.py` and writes the
resulting `logo` URL into this file. Re-run the script when the seed
roster changes.

Tickers not present in the map render with the 2-letter monogram (same
as the on-error fallback inside the `<Glyph>` primitive).
"""
from __future__ import annotations

LOGO_BY_TICKER: dict[str, str] = {
'''
FOOTER = "}\n"


async def main() -> int:
    if not is_configured():
        print("FINNHUB_API_KEY not set — aborting.")
        return 1

    logos: dict[str, str] = {}
    total = len(SP500_SEED)
    for i, row in enumerate(SP500_SEED, start=1):
        ticker = row["ticker"]
        try:
            profile = await company_profile(ticker)
        except Exception as exc:  # noqa: BLE001
            print(f"[{i:>3}/{total}] {ticker:<6} ERROR: {exc}")
            continue
        url = (profile or {}).get("logo")
        if url:
            logos[ticker] = url
            print(f"[{i:>3}/{total}] {ticker:<6} ok")
        else:
            print(f"[{i:>3}/{total}] {ticker:<6} (no logo)")

    body = "".join(
        f'    {repr(t)}: {repr(u)},\n' for t, u in sorted(logos.items())
    )
    OUTPUT.write_text(HEADER + body + FOOTER, encoding="utf-8")
    print(f"\nWrote {len(logos)} entries to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
